# -*- coding: utf-8 -*-
"""scraping financial statements reliance finology 12/11/21

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17u4hRqzycVPixVXDWf4yeCGt2svgCLJJ
"""

import pandas as pd

url="https://ticker.finology.in/company/RELIANCE"

df_list=pd.read_html(url)

print(df_list[0])

print(df_list[1])

print(df_list[2])

print(df_list[3])

print(df_list[4])

print(df_list[5])

print(df_list[6])

